version: '2'
services:
  api8080:
    image: api8080-project5:1.0.0
    container_name: api8080-project5
    ports:
      - "8080:8080"
    networks:
      - fintech-project5
  api8081:
    image: api8081-project5:1.0.0
    container_name: api8081-project5
    ports:
      - "8081:8080"
    networks:
      - fintech-project5
  api8082:
    image: api8082-project5:1.0.0
    container_name: api8082-project5
    ports:
      - "8082:8080"
    networks:
      - fintech-project5
  nginx:
    image: nginx-project5:1.0.0
    container_name: nginx-project5
    ports:
      - "80:80"
    networks:
      - fintech-project5

networks:
  fintech-project5:
    driver: bridge